apiVersion: v1
kind: Pod
metadata:
  name: {{ .name }}
spec:
  containers:
    - name: {{ .name }}
      resources:
        requests:
          memory: "14Gi"
          cpu: "400m"
      image: {{ .image }}
      command:
        [
          "/bin/chainweb-node",
          "--port=443",
          --disable-transaction-index,
          "--log-handle=es:search-tnlogs-eb57oi7cimmanlguprazntbqva.us-east-1.es.amazonaws.com:80",
          "--telemetry-log-handle=es:search-tnlogs-eb57oi7cimmanlguprazntbqva.us-east-1.es.amazonaws.com:80",
        ]
      ports:
        - containerPort: 443
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .name }}
  ports:
    - port: 443
      targetPort: 443
