#!/usr/bin/env sh

# Module Hashes can't be the same, so this is a WONTFIX
mkdir -p diffs/loaded-module-hash
for f in $(grep -Rl parity-replay-diffs/ -e 'Loaded module');
  do mv "$f" diffs/loaded-module-hash/;
done;

# this is not good
mkdir -p diffs/failed-deserialize-module
for f in $(grep -Rl parity-replay-diffs/ -e 'Failed to deserialize but found value at key:free.kor-oracle');
  do mv "$f" diffs/failed-deserialize-module/;
done;

# this is the cap vuln fix *probably*, need to drill down further
mkdir -p diffs/keyset-failure
for f in $(grep -Rl parity-replay-diffs/ -e 'Keyset failure');
  do mv "$f" diffs/keyset-failure/;
done;

# not sure about these
mkdir -p diffs/too-many-arguments
for f in $(grep -Rl parity-replay-diffs/ -e 'Attempted to apply a closure to too many arguments');
  do mv "$f" diffs/too-many-arguments/;
done;

# we'll have to drill down on these
mkdir -p diffs/gas-exceeded
for f in $(grep -Rl parity-replay-diffs/ -e 'GasError');
  do mv "$f" diffs/gas-exceeded/;
done;

# jose says he has a fix for this
mkdir -p diffs/x_resume
for f in $(grep -Rl parity-replay-diffs/ -e 'X_RESUME');
  do mv "$f" diffs/x_resume/;
done;

# not sure about these
mkdir -p diffs/unbound-free-variable
for f in $(grep -Rl parity-replay-diffs/ -e 'Unbound free variable');
  do mv "$f" diffs/unbound-free-variable/;
done;

# not sure about these
mkdir -p diffs/key-not-found
for f in $(grep -Rl parity-replay-diffs/ -e 'Key .* not found in object');
  do mv "$f" diffs/key-not-found/;
done;

# jose has some explanation for this
mkdir -p diffs/expected-bool-got-unit
for f in $(grep -Rl parity-replay-diffs/ -e 'expected bool value, got \(\)');
  do mv "$f" diffs/expected-bool-got-unit/;
done;

# not sure about these
mkdir -p diffs/no-such-key-in-table
for f in $(grep -Rl parity-replay-diffs/ -e 'invariant violated: No such key .* in table');
  do mv "$f" diffs/no-such-key-in-table/;
done;

# just a new message, this is fine
mkdir -p diffs/keyset-defined
for f in $(grep -Rl parity-replay-diffs/ -e 'Keyset write success');
  do mv "$f" diffs/keyset-defined/;
done;

# not sure about these
mkdir -p diffs/wiza-equipped-item
for f in $(grep -Rl parity-replay-diffs/ -e 'equipped');
  do mv "$f" diffs/wiza-equipped-item/;
done;

# we just have a new error message here
mkdir -p diffs/read-keyset-error
for f in $(grep -Rl parity-replay-diffs/ -e 'read-keyset failure');
  do mv "$f" diffs/read-keyset-error/;
done;

# not sure at all
mkdir -p diffs/nft-mint-mystery
for f in $(grep -Rl parity-replay-diffs/ -e 'New reward balance for');
  do mv "$f" diffs/nft-mint-mystery/;
done;

# new error message
mkdir -p diffs/cannot-find-module
for f in $(grep -Rl parity-replay-diffs/ -e 'Cannot resolve');
  do mv "$f" diffs/cannot-find-module/;
done;

# not sure about this
mkdir -p diffs/table-not-found
for f in $(grep -Rl parity-replay-diffs/ -e 'Table .* not found');
  do mv "$f" diffs/table-not-found/;
done;

# new interface loading message
mkdir -p diffs/interface-loaded
for f in $(grep -Rl parity-replay-diffs/ -e 'Loaded interface');
  do mv "$f" diffs/interface-loaded/;
done;

# unsure
mkdir -p diffs/minimum-precision
for f in $(grep -Rl parity-replay-diffs/ -e 'Amount violates minimum precision');
  do mv "$f" diffs/minimum-precision;
done;


# Code that implicitly grabs module admin which is no longer allowed
# will require going through these to see the extent of the breakage
mkdir -p diffs/module-admin
for f in $(grep -Rl parity-replay-diffs/ -e 'Module admin necessary');
  do mv "$f" diffs/module-admin
done;

# has no such member
mkdir -p diffs/no-such-member
for f in $(grep -Rl parity-replay-diffs/ -e 'has no such member');
  do mv "$f" diffs/no-such-member
done;

mkdir -p diffs/insert-ok
for f in $(grep -Rl parity-replay-diffs/ -e 'Insert: row found for key');
  do mv "$f" diffs/insert-ok
done;

mkdir -p diffs/capability-already-installed
for f in $(grep -Rl parity-replay-diffs/ -e 'Capability already installed');
  do mv "$f" diffs/capability-already-installed
done;

mkdir -p diffs/token-protocol-violation
for f in $(grep -Rl parity-replay-diffs/ -e 'Token protocol violation');
  do mv "$f" diffs/token-protocol-violation
done;

mkdir -p diffs/failed-to-call-at
for f in $(grep -Rl parity-replay-diffs/ -e 'failed to call native function at with argument(s) of type(s)');
  do mv "$f" diffs/failed-to-call-at
done;

# LIQUIDITY_POS_GUARD
mkdir -p diffs/liq-pos-guard
for f in $(grep -Rl parity-replay-diffs/ -e 'LIQUIDITY_POS_GUARD');
  do mv "$f" diffs/liq-pos-guard
done;

# {"status":"success","data":{"int"
mkdir -p diffs/output-differs-int-double
for f in $(grep -Rl parity-replay-diffs/ -e '{"status":"success","data":{"int"');
  do mv "$f" diffs/output-differs-int-double
done;

# No pact exec
mkdir -p diffs/no-pact-exec-in-cr
for f in $(grep -Rl parity-replay-diffs/ -e 'Continuation Error: verifyCont');
  do mv "$f" diffs/no-pact-exec-in-cr
done;


# Not sure
mkdir -p diffs/table-already-exists
for f in $(grep -Rl parity-replay-diffs/ -e 'Table .* already exists');
  do mv "$f" diffs/table-already-exists
done;


# Not sure
mkdir -p diffs/non-pact-value
for f in $(grep -Rl parity-replay-diffs/ -e 'Expected Pact Value, got closure or table reference');
  do mv "$f" diffs/non-pact-value
done;

#
mkdir -p diffs/quiz-results
for f in $(grep -Rl parity-replay-diffs/ -e '"source":"quiz_');
  do mv "$f" diffs/quiz-results
done;

#
mkdir -p diffs/read-function-failures
for f in $(grep -Rl parity-replay-diffs/ -e 'read-decimal failure');
  do mv "$f" diffs/read-function-failures
done;

for f in $(grep -Rl parity-replay-diffs/ -e 'No such key in message');
  do mv "$f" diffs/read-function-failures
done;

mkdir -p diffs/lago-finance
for f in $(grep -Rl parity-replay-diffs/ -e 'Runtime typecheck failure, argument is table , but expected type object');
  do mv "$f" diffs/lago-finance
done;

# db errorError
mkdir -p diffs/db-internal-error
for f in $(grep -Rl parity-replay-diffs/ -e 'callDb (doReadRow): user error (Database error: ErrorError)');
  do mv "$f" diffs/db-internal-error
done;

# Invalid arguments in call to if
mkdir -p diffs/invalid-call-to-if
for f in $(grep -Rl parity-replay-diffs/ -e 'Invalid arguments in call to if');
  do mv "$f" diffs/invalid-call-to-if
done;

# cannot compare incompatible types
mkdir -p diffs/incompatible-types
for f in $(grep -Rl parity-replay-diffs/ -e 'cannot compare incompatible types');
  do mv "$f" diffs/incompatible-types
done;

# cannot compare incompatible types
mkdir -p diffs/b64-diffs
for f in $(grep -Rl parity-replay-diffs/ -e 'invalid b64');
  do mv "$f" diffs/b64-diffs
done;

mkdir -p diffs/interface-as-mod-ref
for f in $(grep -Rl parity-replay-diffs/ -e 'Invalid Interface attempted to be used as module reference');
  do mv "$f" diffs/interface-as-mod-ref
done;

# Marmalade mints
mkdir -p diffs/marmalade-mints
for f in $(grep -Rl parity-replay-diffs/ -e '"module":{"namespace":"marmalade","name":"ledger"}');
  do mv "$f" diffs/marmalade-mints
done;

# Marmalade mints
mkdir -p diffs/marmalade-v2
for f in $(grep -Rl parity-replay-diffs/ -e '"module":{"namespace":"marmalade-v2","name":"ledger"}');
  do mv "$f" diffs/marmalade-v2
done;

mkdir -p diffs/kadena-mining-club
for f in $(grep -Rl parity-replay-diffs/ -e '"module":{"namespace":"free","name":"kadena-mining-club"}');
  do mv "$f" diffs/kadena-mining-club
done;

for f in $(grep -Rl parity-replay-diffs/ -e '{"status":"success","data":"Price updated to');
  do mv "$f" diffs/kadena-mining-club
done;

mkdir -p diffs/kadena-mining-club-format
for f in $(grep -Rl diffs/kadena-mining-club/ -e 'Invalid arguments in call to format');
  do mv "$f" diffs/kadena-mining-club-format
done;

mkdir -p diffs/interface-impl-errors
for f in $(grep -Rl parity-replay-diffs/ -e 'does not correctly implement the function');
  do mv "$f" diffs/interface-impl-errors
done;

mkdir -p diffs/minimum-precision
for f in $(grep -Rl parity-replay-diffs/ -e 'Amount violates minimum denomination');
  do mv "$f" diffs/minimum-precision
done;

mkdir -p diffs/dao-hive-factory
for f in $(grep -Rl parity-replay-diffs/ -e 'dao-hive-factory');
  do mv "$f" diffs/dao-hive-factory
done;

#
mkdir -p diffs/invalid-def-in-term-var
for f in $(grep -Rl parity-replay-diffs/ -e 'Invalid definition in term variable position');
  do mv "$f" diffs/invalid-def-in-term-var
done;

#
mkdir -p diffs/desugar-syntax-failure
for f in $(grep -Rl parity-replay-diffs/ -e 'Desugar syntax failure');
  do mv "$f" diffs/desugar-syntax-failure
done;

# PactDuplicateTableError
mkdir -p diffs/duplicate-table-error
for f in $(grep -Rl parity-replay-diffs/ -e 'PactDuplicateTableError');
  do mv "$f" diffs/duplicate-table-error
done;

# Cap already installed
mkdir -p diffs/cap-is-not-managed
for f in $(grep -Rl parity-replay-diffs/ -e 'capability is not managed and cannot be installed');
  do mv "$f" diffs/cap-is-not-managed
done;

mkdir -p diffs/kedao
for f in $(grep -Rl parity-replay-diffs/ -e 'kedao');
  do mv "$f" diffs/kedao
done;


mkdir -p diffs/interesting
mv parity-replay-diffs/_HFqdbIlHNdS8wNgMdNGlkkuhjD4ZllxNL7fTg6EhO0.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/TFcV7ZlgIUavNezrrMjv_40-s3rYwxXdN9hAuSX52yo.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/XKGDNtQNgeGTUQwclhSu5Bzat3XNzClDh_teQ_ET4zE.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/IERmriVgG_Y5FLBMSAb0s70wuq8vFmRheSxALFPArrg.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/1q7J661naTNdALjAow6N0FdNwWUD2qDKI7H2ah594xw.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/KBZEw8l7d3pSwVmEDgPZ8lsNT9xZL1KOI3zYJymLfj8.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/iZTMwypb6iyq85e9lryzMstcoHkM-B6ihG95AhPRk_M.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/2WUTwvO39Z0izsAP1xZsa7cQHtVlxHR2S4ldBdsWUMA.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/pqpNMUvjBmflJEwRbka4pugkfOw3_bloewnfGZ6i4LE.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/jiZrj-NUMGEp1XcVni3gufkjtYItszFd1zjV66hRwhE.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/Akt5RUolyR4bzS2u0xpDrMoR5PdLAHKHp1h4HpBcVVo.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/0wpwNj7bvh4y9Ax_zmjHzRiKa96pc2Co1ZeDFNK7oac.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/uZrgs9xLthCx-bc53_drXnRSkra4pf9ddw65fC_ZGm4.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/-WQoBV7Ah6VVYtvkkiQ8eIcXeQx_MymbtWW6NxpmPBU.md diffs/interesting 2> /dev/null

# Format list commas
mv parity-replay-diffs/ijcy5AXfsShzvXbGK9olHUNH3TETD6D-i9CV172nlg8.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/eXq55WivCpojMa20KjK35uCurSHZVvkZmDggkX4fOuI.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/VqL6Z6IBs7KOyHAiVNgnrdbysO5KYsJ2A2-HWGYc2eo.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/uR88qo2v4EPLGxqUfuslJOeeD_QUVKzZE5mY6XauAr8.md diffs/interesting 2> /dev/null

mv parity-replay-diffs/14RYfa6_zc8UTWPNyMOqV00jfApmk6spD3v9z7OvwWA.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/AtlJbN56F2H_ibfuOfepu3NNiVMy8i9SJp6NIUZUkqM.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/D1cMZW_len_iahiowulPTebPAK0Quk-v20R_3H788iE.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/F4rREqcjnX4Rztsxu4zKX6r_lMRCSAtiZcsjAehTdCE.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/J4KyKYgAiW8_OTZEZd8CmAMzdWUk6EYSg9GKHUkPImA.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/JhytcMWLjNGQpDXUtggon3mtwoxvsycr7vfnV-DFHtQ.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/OdPvy5wglBEBlzShcVqteVeOhl1y9_wKP9JhNoaxEe0.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/QOCbuI9-WMG-GoiI7vkgRibFO6PEDu4A2SeVMpAuACw.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/U5WaTSf9UZ1TCJr3bAxa9iy-205aGjzAH-ESi42Om4k.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/Whq99lwfCvAYWI9ey8fVND3p8jVrTGfBwsu9IXEYGyc.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/XPNOBrNUUZChmn8CVOV-CKg0xJse0uu25MVpmT-mfH0.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/Xx8Kt_4YePIND13ZVq8F9grrxzNLCyV-KisBmtO8HMw.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/ZlCeumS6KmXBRp9M5B-Hd0w2r49iaj874jbHT-ELDDg.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/gRqhSl-5-U_l77W-5cgryrFU_L5hwY6XJTgNLSU3tTI.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/ijiMoA3JgIDgdol5va92QBtfpw1rFGJjN5Lz36hgBzs.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/lLoPxT_J0gbB1GzGkcjmAWt1fph8kMfJrsRoHZQf8Sw.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/lewljJ2a40a9nMHTncarl3Se3ZBgHYkxV9TJbgfEGks.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/mSKGH1KhSQIY_FpWWXrUimKh1QQALYGfnv4f1Nn28Hk.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/mXl9L4xl8pzrK8tOf2PVEKF-AmtofRnOZmvy4MX4Rc8.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/oXynyHlhJgoT2YEl-JSSUbWO95DGOU6aO08QrYVpvNU.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/uHM_66xiDIxpB9CQzxKoNbtYfJ6hkfl1PU_2PvAyl4E.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/uQrg01VcUBUoNeZgQ22MukbUrAN4l9AIzUiCOlhVp6I.md diffs/interesting 2> /dev/null
mv parity-replay-diffs/wKWF6E3-kuuhAn7o9vPY9amI8oN5RjROaZlwVHPp4B0.md diffs/interesting 2> /dev/null

# diffCount=$(find parity-replay-diffs -type f -exec echo -n "." \; | wc -c)
# file_count=$(find parity-replay-diffs -type f -exec echo -n "." \; | wc -c)

# echo "Remaining diffs: $diffCount"
# Check if there are any files remaining
# if [ "$file_count" -gt 0 ]; then
#   echo "Number of files: $file_count"
#   echo "Remaining files:"
#   find parity-replay-diffs -type f
# else
#   echo "No files remaining."
# fi
