#!/usr/bin/env sh

mkdir -p diffs/loaded-module-hash/
mkdir -p diffs/failed-deserialize-module
mkdir -p diffs/keyset-failure
mkdir -p diffs/too-many-arguments
mkdir -p diffs/gas-exceeded
mkdir -p diffs/x_resume
mkdir -p diffs/unbound-free-variable
mkdir -p diffs/expected-bool-got-unit
mkdir -p diffs/no-such-key-in-table
mkdir -p diffs/keyset-defined
mkdir -p diffs/wiza-equipped-item
mkdir -p diffs/read-keyset-error
mkdir -p diffs/nft-mint-mystery
mkdir -p diffs/cannot-find-module
mkdir -p diffs/table-not-found
mkdir -p diffs/interface-loaded
mkdir -p diffs/minimum-precision
mkdir -p diffs/module-admin
mkdir -p diffs/no-such-member
mkdir -p diffs/insert-ok
mkdir -p diffs/capability-already-installed
mkdir -p diffs/token-protocol-violation
mkdir -p diffs/failed-to-call-at
mkdir -p diffs/liq-pos-guard
mkdir -p diffs/output-differs-int-double
mkdir -p diffs/no-pact-exec-in-cr
mkdir -p diffs/table-already-exists
mkdir -p diffs/non-pact-value
mkdir -p diffs/quiz-results
mkdir -p diffs/read-function-failures
mkdir -p diffs/read-function-failures
mkdir -p diffs/lago-finance
mkdir -p diffs/db-internal-error
mkdir -p diffs/invalid-call-to-if
mkdir -p diffs/incompatible-types
mkdir -p diffs/b64-diffs
mkdir -p diffs/interface-as-mod-ref
mkdir -p diffs/marmalade-mints
mkdir -p diffs/marmalade-v2
mkdir -p diffs/kadena-mining-club
mkdir -p diffs/kadena-mining-club
mkdir -p diffs/kadena-mining-club-format
mkdir -p diffs/interface-impl-errors
mkdir -p diffs/minimum-precision
mkdir -p diffs/dao-hive-factory
mkdir -p diffs/invalid-def-in-term-var
mkdir -p diffs/desugar-syntax-failure
mkdir -p diffs/duplicate-table-error
mkdir -p diffs/cap-is-not-managed
mkdir -p diffs/kedao

classify_diff() {
  grep -q 'Loaded module' "$1" && mv "$1" diffs/loaded-module-hash/ && return
  grep -q 'Failed to deserialize but found value at key:free.kor-oracle' "$1" && mv "$1" diffs/failed-deserialize-module && return
  grep -q 'Keyset failure' "$1" && mv "$1" diffs/keyset-failure && return
  grep -q 'Attempted to apply a closure to too many arguments' "$1" && mv "$1" diffs/too-many-arguments && return
  grep -q 'GasError' "$1" && mv "$1" diffs/gas-exceeded && return
  grep -q 'X_RESUME' "$1" && mv "$1" diffs/x_resume && return
  grep -q 'Unbound free variable' "$1" && mv "$1" diffs/unbound-free-variable && return
  grep -q 'expected bool value, got \(\)' "$1" && mv "$1" diffs/expected-bool-got-unit && return
  grep -q 'invariant violated: No such key .* in table' "$1" && mv "$1" diffs/no-such-key-in-table && return
  grep -q 'Keyset write success' "$1" && mv "$1" diffs/keyset-defined && return
  grep -q 'equipped' "$1" && mv "$1" diffs/wiza-equipped-item && return
  grep -q 'read-keyset failure' "$1" && mv "$1" diffs/read-keyset-error && return
  grep -q 'New reward balance for' "$1" && mv "$1" diffs/nft-mint-mystery && return
  grep -q 'Cannot resolve' "$1" && mv "$1" diffs/cannot-find-module && return
  grep -q 'Table .* not found' "$1" && mv "$1" diffs/table-not-found && return
  grep -q 'Loaded interface' "$1" && mv "$1" diffs/interface-loaded && return
  grep -q 'Amount violates minimum precision' "$1" && mv "$1" diffs/minimum-precision && return
  grep -q 'Module admin necessary' "$1" && mv "$1" diffs/module-admin && return
  grep -q 'has no such member' "$1" && mv "$1" diffs/no-such-member && return
  grep -q 'Insert: row found for key' "$1" && mv "$1" diffs/insert-ok && return
  grep -q 'Capability already installed' "$1" && mv "$1" diffs/capability-already-installed && return
  grep -q 'Token protocol violation' "$1" && mv "$1" diffs/token-protocol-violation && return
  grep -q 'failed to call native function at with argument(s) of type(s)' "$1" && mv "$1" diffs/failed-to-call-at && return
  grep -q 'LIQUIDITY_POS_GUARD' "$1" && mv "$1" diffs/liq-pos-guard && return
  grep -q '{"status":"success","data":{"int"' "$1" && mv "$1" diffs/output-differs-int-double && return
  grep -q 'Continuation Error: verifyCont' "$1" && mv "$1" diffs/no-pact-exec-in-cr && return
  grep -q 'Table .* already exists' "$1" && mv "$1" diffs/table-already-exists && return
  grep -q 'Expected Pact Value, got closure or table reference' "$1" && mv "$1" diffs/non-pact-value && return
  grep -q '"source":"quiz_' "$1" && mv "$1" diffs/quiz-results && return
  grep -q 'read-decimal failure' "$1" && mv "$1" diffs/read-function-failures && return
  grep -q 'No such key in message' "$1" && mv "$1" diffs/read-function-failures && return
  grep -q 'Runtime typecheck failure, argument is table , but expected type object' "$1" && mv "$1" diffs/lago-finance && return
  grep -q 'callDb (doReadRow): user error (Database error: ErrorError)' "$1" && mv "$1" diffs/db-internal-error && return
  grep -q 'Invalid arguments in call to if' "$1" && mv "$1" diffs/invalid-call-to-if && return
  grep -q 'cannot compare incompatible types' "$1" && mv "$1" diffs/incompatible-types && return
  grep -q 'invalid b64' "$1" && mv "$1" diffs/b64-diffs && return
  grep -q 'Invalid Interface attempted to be used as module reference' "$1" && mv "$1" diffs/interface-as-mod-ref && return
  grep -q '"module":{"namespace":"marmalade","name":"ledger"}' "$1" && mv "$1" diffs/marmalade-mints && return
  grep -q '"module":{"namespace":"marmalade-v2","name":"ledger"}' "$1" && mv "$1" diffs/marmalade-v2 && return
  grep -q '"module":{"namespace":"free","name":"kadena-mining-club"}' "$1" && mv "$1" diffs/kadena-mining-club && return
  grep -q '{"status":"success","data":"Price updated to' "$1" && mv "$1" diffs/kadena-mining-club && return
  grep -q 'Invalid arguments in call to format' "$1" && mv "$1" diffs/kadena-mining-club-format && return
  grep -q 'does not correctly implement the function' "$1" && mv "$1" diffs/interface-impl-errors && return
  grep -q 'Amount violates minimum denomination' "$1" && mv "$1" diffs/minimum-precision && return
  grep -q 'dao-hive-factory' "$1" && mv "$1" diffs/dao-hive-factory && return
  grep -q 'Invalid definition in term variable position' "$1" && mv "$1" diffs/invalid-def-in-term-var && return
  grep -q 'Desugar syntax failure' "$1" && mv "$1" diffs/desugar-syntax-failure && return
  grep -q 'PactDuplicateTableError' "$1" && mv "$1" diffs/duplicate-table-error && return
  grep -q 'capability is not managed and cannot be installed' "$1" && mv "$1" diffs/cap-is-not-managed && return
  grep -q 'kedao' "$1" && mv "$1" diffs/kedao && return
}

for f in parity-replay-diffs/*; do
  classify_diff "$f" &
done;
wait;

mkdir -p diffs/sort-object-divergence
mv parity-replay-diffs/DWbywTHYKnP4M_G4xcOkKy3wuSKIE2INlkJVTX67cZA.md diffs/sort-object-divergence 2> /dev/null

#  mkdir -p diffs/interesting
#  mv parity-replay-diffs/_HFqdbIlHNdS8wNgMdNGlkkuhjD4ZllxNL7fTg6EhO0.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/TFcV7ZlgIUavNezrrMjv_40-s3rYwxXdN9hAuSX52yo.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/XKGDNtQNgeGTUQwclhSu5Bzat3XNzClDh_teQ_ET4zE.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/IERmriVgG_Y5FLBMSAb0s70wuq8vFmRheSxALFPArrg.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/1q7J661naTNdALjAow6N0FdNwWUD2qDKI7H2ah594xw.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/KBZEw8l7d3pSwVmEDgPZ8lsNT9xZL1KOI3zYJymLfj8.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/iZTMwypb6iyq85e9lryzMstcoHkM-B6ihG95AhPRk_M.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/2WUTwvO39Z0izsAP1xZsa7cQHtVlxHR2S4ldBdsWUMA.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/pqpNMUvjBmflJEwRbka4pugkfOw3_bloewnfGZ6i4LE.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/jiZrj-NUMGEp1XcVni3gufkjtYItszFd1zjV66hRwhE.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/Akt5RUolyR4bzS2u0xpDrMoR5PdLAHKHp1h4HpBcVVo.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/0wpwNj7bvh4y9Ax_zmjHzRiKa96pc2Co1ZeDFNK7oac.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/uZrgs9xLthCx-bc53_drXnRSkra4pf9ddw65fC_ZGm4.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/-WQoBV7Ah6VVYtvkkiQ8eIcXeQx_MymbtWW6NxpmPBU.md diffs/interesting 2> /dev/null

#  # Format list commas
#  mv parity-replay-diffs/ijcy5AXfsShzvXbGK9olHUNH3TETD6D-i9CV172nlg8.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/eXq55WivCpojMa20KjK35uCurSHZVvkZmDggkX4fOuI.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/VqL6Z6IBs7KOyHAiVNgnrdbysO5KYsJ2A2-HWGYc2eo.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/uR88qo2v4EPLGxqUfuslJOeeD_QUVKzZE5mY6XauAr8.md diffs/interesting 2> /dev/null

#  mv parity-replay-diffs/14RYfa6_zc8UTWPNyMOqV00jfApmk6spD3v9z7OvwWA.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/AtlJbN56F2H_ibfuOfepu3NNiVMy8i9SJp6NIUZUkqM.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/D1cMZW_len_iahiowulPTebPAK0Quk-v20R_3H788iE.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/F4rREqcjnX4Rztsxu4zKX6r_lMRCSAtiZcsjAehTdCE.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/J4KyKYgAiW8_OTZEZd8CmAMzdWUk6EYSg9GKHUkPImA.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/JhytcMWLjNGQpDXUtggon3mtwoxvsycr7vfnV-DFHtQ.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/OdPvy5wglBEBlzShcVqteVeOhl1y9_wKP9JhNoaxEe0.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/QOCbuI9-WMG-GoiI7vkgRibFO6PEDu4A2SeVMpAuACw.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/U5WaTSf9UZ1TCJr3bAxa9iy-205aGjzAH-ESi42Om4k.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/Whq99lwfCvAYWI9ey8fVND3p8jVrTGfBwsu9IXEYGyc.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/XPNOBrNUUZChmn8CVOV-CKg0xJse0uu25MVpmT-mfH0.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/Xx8Kt_4YePIND13ZVq8F9grrxzNLCyV-KisBmtO8HMw.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/ZlCeumS6KmXBRp9M5B-Hd0w2r49iaj874jbHT-ELDDg.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/gRqhSl-5-U_l77W-5cgryrFU_L5hwY6XJTgNLSU3tTI.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/ijiMoA3JgIDgdol5va92QBtfpw1rFGJjN5Lz36hgBzs.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/lLoPxT_J0gbB1GzGkcjmAWt1fph8kMfJrsRoHZQf8Sw.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/lewljJ2a40a9nMHTncarl3Se3ZBgHYkxV9TJbgfEGks.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/mSKGH1KhSQIY_FpWWXrUimKh1QQALYGfnv4f1Nn28Hk.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/mXl9L4xl8pzrK8tOf2PVEKF-AmtofRnOZmvy4MX4Rc8.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/oXynyHlhJgoT2YEl-JSSUbWO95DGOU6aO08QrYVpvNU.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/uHM_66xiDIxpB9CQzxKoNbtYfJ6hkfl1PU_2PvAyl4E.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/uQrg01VcUBUoNeZgQ22MukbUrAN4l9AIzUiCOlhVp6I.md diffs/interesting 2> /dev/null
#  mv parity-replay-diffs/wKWF6E3-kuuhAn7o9vPY9amI8oN5RjROaZlwVHPp4B0.md diffs/interesting 2> /dev/null

 # diffCount=$(find parity-replay-diffs -type f -exec echo -n "." \; | wc -c)
 # file_count=$(find parity-replay-diffs -type f -exec echo -n "." \; | wc -c)

 # echo "Remaining diffs: $diffCount"
 # Check if there are any files remaining
 # if [ "$file_count" -gt 0 ]; then
 #   echo "Number of files: $file_count"
 #   echo "Remaining files:"
 #   find parity-replay-diffs -type f
 # else
 #   echo "No files remaining."
 # fi
