resolver: lts-16.0

build:
  test-arguments:
    additional-args: ["--hide-successes", "--color", "never"]

flags:
  pact:
    build-tool: false

extra-deps:
  # --- Missing from Stackage --- #
  - configuration-tools-0.6.0
  - digraph-0.2.1
  - fake-0.1.1.3
  - ixset-typed-0.5
  - loglevel-0.1.0.0
  - merkle-log-0.1.1
  - paths-0.2.0.0
  - random-strings-0.1.1.0
  - streaming-concurrency-0.3.1.3
  - streaming-events-1.0.0
  - streaming-with-0.2.2.1
  - strict-tuple-0.1.3
  - tasty-json-0.1.0.0
  - token-bucket-0.1.0.1
  - wai-middleware-throttle-0.3.0.1
  - yet-another-logger-0.4.0
  - cuckoo-0.2.2
  - random-1.2.0
  - nothunks-0.1.2
  - network-3.1.2.2

  # random 1.2
  - splitmix-0.1.0.3
  - uuid-1.3.14
  - uuid-types-1.0.4
  - QuickCheck-2.14.2

  # QuickCheck
  - servant-0.18.2
  - servant-client-0.18.2
  - servant-client-core-0.18.2
  - servant-server-0.18.2
  - quickcheck-instances-0.3.25.2

  # quickcheck-instances
  - data-fix-0.3.1
  - strict-0.4.0.1
  - these-1.1.1.1
  - time-compat-1.9.5

  # --- Transitive Pact Dependencies --- #
  - direct-sqlite-2.3.26
  - ed25519-donna-0.1.1
  - prettyprinter-1.6.0
  - megaparsec-9.0.0
  - pact-time-0.2.0.0

  # --- Custom Pins --- #
  - github: kadena-io/pact
    commit: ef4f089d50b5f0c19b2d6aaea80e6e2dccb0f153
  - github: kadena-io/chainweb-storage
    commit: bf37c394de9a0c680a7a09bbfb82eb255519b3fb
  - github: kadena-io/rosetta
    commit: 5db55e77e7f0ffe7670075708843fa03d179aaa5
  - github: kadena-io/kadena-ethereum-bridge
    commit: 10f21e96af1dce4f13e261be9dfad8c28cd299f7
