resolver: lts-14.27

#ghc-options: {"$locals": -ddump-to-file -ddump-hi}

extra-deps:
  # --- Missing from Stackage --- #
  - QuickCheck-GenT-0.2.0
  - bloomfilter-2.0.1.0
  - digraph-0.1.0.2
  - fake-0.1.1.2
  - loglevel-0.1.0.0
  - merkle-log-0.1.0.0
  - paths-0.2.0.0
  - streaming-events-1.0.0
  - strict-tuple-0.1.3
  - yet-another-logger-0.4.0
  - configuration-tools-0.5.0
  - random-strings-0.1.1.0
  - streaming-concurrency-0.3.1.3
  - streaming-with-0.2.2.1

  # --- Transitive Pact Dependencies --- #
  - ed25519-donna-0.1.1
  - megaparsec-8.0.0
  - sbv-8.2
  - trifecta-2.1
  - github: kadena-io/thyme
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9

  # --- Forced Upgrades --- #
  - generic-lens-1.2.0.1  # For generic newtype unwrapping
  - lens-aeson-1.1
  - tls-1.5.4
  - tls-session-manager-0.0.4
  - warp-3.3.9
  - warp-tls-3.2.11

  # --- Custom Pins --- #
  - github: kadena-io/pact
    commit: 3479b2f7f9d5cb19043baace614ea3539c429ed0
  - github: kadena-io/chainweb-storage
    commit: 07e7eb7596c7105aee42dbdb6edd10e3f23c0d7e

build:
  test-arguments:
    additional-args: ["--hide-successes", "--color", "never"]

# cache bump
