resolver: lts-14.17

#ghc-options: {"$locals": -ddump-to-file -ddump-hi}

extra-deps:
  # --- Missing from Stackage --- #
  - QuickCheck-GenT-0.2.0
  - bloomfilter-2.0.1.0
  - digraph-0.1.0.2
  - fake-0.1.1.2
  - loglevel-0.1.0.0
  - merkle-log-0.1.0.0
  - paths-0.2.0.0
  - streaming-events-1.0.0
  - strict-tuple-0.1.3
  - yet-another-logger-0.3.1
  - random-strings-0.1.1.0

  # --- Transitive Pact Dependencies --- #
  - ed25519-donna-0.1.1
  - sbv-8.2
  - trifecta-2.1
  - github: kadena-io/thyme
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9

  # --- Forced Upgrades --- #
  - generic-lens-1.2.0.1  # For generic newtype unwrapping
  - http2-2.0.3
  - tls-1.5.2
  - warp-3.3.5
  - warp-tls-3.2.9

  # --- Custom Pins --- #
  - github: kadena-io/pact
    commit: d54697ad5368263b98f2bf0c2ac4d7b065b0f5bf
  - github: kadena-io/chainweb-storage
    commit: 17a5fb130926582eff081eeb1b94cb6c7097c67a
