resolver: lts-12.26

extra-deps:
  # --- Missing from Stackage --- #
  - QuickCheck-GenT-0.2.0
  - bloomfilter-2.0.1.0
  - digraph-0.1.0.0
  - fake-0.1.1.2
  - fast-builder-0.1.0.1
  - loglevel-0.1.0.0
  - merkle-log-0.1.0.0
  - paths-0.2.0.0
  - rocksdb-haskell-1.0.1
  - strict-tuple-0.1.2
  - wai-middleware-throttle-0.3.0.0
  - yet-another-logger-0.3.1

  # --- Forced Dependencies --- #
  - ed25519-donna-0.1.1  # Due to Pact
  - hspec-2.7.0          # Due to QuickCheck
  - hspec-core-2.7.0     # Due to QuickCheck
  - hspec-discover-2.7.0 # Due to QuickCheck
  - libyaml-0.1.1.0      # Due to yaml
  - massiv-0.3.3.0       # Due to digraph
  - mwc-random-0.14.0.0  # Due to digraph
  - sbv-8.2              # Due to Pact
  - scheduler-1.3.0      # Due to massiv
  - splitmix-0.0.2       # Due to QuickCheck
  - token-bucket-0.1.0.1 # Due to wai-middleware-throttle

  # --- Forced Upgrades --- #
  - QuickCheck-2.12.6.1
  - aeson-1.4.3.0
  - configuration-tools-0.4.1
  - generic-lens-1.1.0.0
  - nonempty-containers-0.2.0.0
  - tasty-1.2
  - vector-algorithms-0.8.0.1
  - yaml-0.11.0.0

  # --- Custom Pins --- #
  - git: https://github.com/kadena-io/pact.git
    commit: f880d34850b5aa4bd538a23029a74777e1f83a5d
  - git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
