resolver: lts-16.0

build:
  test-arguments:
    additional-args: ["--hide-successes", "--color", "never"]

extra-deps:
  # --- Missing from Stackage --- #
  - configuration-tools-0.6.0
  - digraph-0.2
  - fake-0.1.1.3
  - ixset-typed-0.5
  - loglevel-0.1.0.0
  - merkle-log-0.1.0.0
  - paths-0.2.0.0
  - random-strings-0.1.1.0
  - streaming-concurrency-0.3.1.3
  - streaming-events-1.0.0
  - streaming-with-0.2.2.1
  - strict-tuple-0.1.3
  - tasty-json-0.1.0.0
  - token-bucket-0.1.0.1
  - wai-middleware-throttle-0.3.0.1
  - yet-another-logger-0.4.0
  - cuckoo-0.2.1
  - random-1.2.0

  # random 1.2
  - splitmix-0.1.0.3
  - uuid-1.3.14
  - uuid-types-1.0.4
  - QuickCheck-2.14.2

  # QuickCheck
  - servant-0.18.2
  - servant-client-0.18.2
  - servant-client-core-0.18.2
  - servant-server-0.18.2
  - quickcheck-instances-0.3.25.2

  # quickcheck-instances
  - data-fix-0.3.1
  - strict-0.4.0.1
  - these-1.1.1.1
  - time-compat-1.9.5

  # --- Forced Downgrades --- #
  - network-3.1.0.1

  # --- Transitive Pact Dependencies --- #
  - direct-sqlite-2.3.26
  - ed25519-donna-0.1.1
  - prettyprinter-1.6.0
  - sbv-8.8
  - neat-interpolation-0.5.1.2
  - megaparsec-9.0.0
  - pact-time-0.2.0.0

  # --- Custom Pins --- #
  - github: kadena-io/pact
    commit: 853d255202d590e133aed16ee8a117b55e9bc623
  - github: kadena-io/chainweb-storage
    commit: 07e7eb7596c7105aee42dbdb6edd10e3f23c0d7e
  - github: kadena-io/rosetta
    commit: 1d69bb4ec46c001f2b501121e6c93e83ac60162b
  - github: kadena-io/kadena-ethereum-bridge
    commit: 9838d1266b9ee43c88af6c01cd819e0c96b685e6
