resolver: lts-16.0

build:
  test-arguments:
    additional-args: ["--hide-successes", "--color", "never"]

extra-deps:
  # --- Missing from Stackage --- #
  - bloomfilter-2.0.1.0
  - configuration-tools-0.5.0
  - digraph-0.2
  - fake-0.1.1.3
  - ixset-typed-0.5
  - loglevel-0.1.0.0
  - merkle-log-0.1.0.0
  - paths-0.2.0.0
  - random-strings-0.1.1.0
  - streaming-concurrency-0.3.1.3
  - streaming-events-1.0.0
  - streaming-with-0.2.2.1
  - strict-tuple-0.1.3
  - tasty-json-0.1.0.0
  - these-skinny-0.7.4
  - token-bucket-0.1.0.1
  - wai-middleware-throttle-0.3.0.1
  - yet-another-logger-0.4.0

  # --- Forced Downgrades --- #
  - network-3.1.0.1

  # --- Transitive Pact Dependencies --- #
  - direct-sqlite-2.3.26
  - ed25519-donna-0.1.1
  - prettyprinter-1.6.0
  - sbv-8.7
  - github: kadena-io/thyme
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9

  # --- Custom Pins --- #
  - github: kadena-io/pact
    commit: 94cfeb57e2f90c299fc27cc3e72f6b6aa9109c06
  - github: kadena-io/chainweb-storage
    commit: 07e7eb7596c7105aee42dbdb6edd10e3f23c0d7e
  - github: kadena-io/rosetta
    commit: 1ccb68d7aec0414f494fb06f591214e7cf845627
