resolver: lts-14.14

#ghc-options: {"$locals": -ddump-to-file -ddump-hi -funclutter-valid-hole-fits -fmax-relevant-binds=0}

extra-deps:
  # --- Missing from Stackage --- #
  - QuickCheck-GenT-0.2.0
  - bloomfilter-2.0.1.0
  - digraph-0.1.0.2
  - fake-0.1.1.2
  - loglevel-0.1.0.0
  - merkle-log-0.1.0.0
  - paths-0.2.0.0
  - streaming-events-1.0.0
  - strict-tuple-0.1.3
  - yet-another-logger-0.3.1
  - random-strings-0.1.1.0
  # --- Transitive Pact Dependencies --- #
  - ed25519-donna-0.1.1
  - sbv-8.2
  - trifecta-2.1
  - github: kadena-io/thyme
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9

  # --- Forced Upgrades --- #
  - generic-lens-1.2.0.0  # For generic newtype unwrapping
  - tls-1.5.2

  # --- Custom Pins --- #
  - github: kadena-io/pact
    commit: 3763fecf23122cdd2352377564f3c47dc497ee17
  - github: kadena-io/chainweb-storage
    commit: 17a5fb130926582eff081eeb1b94cb6c7097c67a
