resolver: lts-13.26

extra-deps:
  # --- Missing from Stackage --- #
  - QuickCheck-GenT-0.2.0
  - bloomfilter-2.0.1.0
  - digraph-0.1.0.2
  - fake-0.1.1.2
  - fast-builder-0.1.0.1
  - loglevel-0.1.0.0
  - merkle-log-0.1.0.0
  - paths-0.2.0.0
  - strict-tuple-0.1.2
  - yet-another-logger-0.3.1

  # --- Transitive Pact Dependencies --- #
  - prettyprinter-convert-ansi-wl-pprint-1.1
  - ed25519-donna-0.1.1
  - megaparsec-6.5.0

  # --- Other Transitive Dependencies --- #
  - massiv-0.3.5.0             # Due to digraph
  - scheduler-1.4.0            # Due to massiv
  - neat-interpolation-0.3.2.2 # Due to megaparsec

  # --- Forced Upgrades --- #
  - aeson-1.4.3.0
  - nonempty-containers-0.2.0.0
  - sbv-8.2
  - tls-1.5.0

  # --- Custom Pins --- #
  - github: kadena-io/pact
    commit: d10173c574ae4dce1dae5a5dcbaf1ec4a9feb2c3
  - github: kadena-io/thyme
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
