resolver: lts-12.26

extra-deps:
  # --- Missing from Stackage --- #
  - QuickCheck-GenT-0.2.0
  - bloomfilter-2.0.1.0
  - digraph-0.1.0.2
  - fake-0.1.1.2
  - fast-builder-0.1.0.1
  - loglevel-0.1.0.0
  - merkle-log-0.1.0.0
  - paths-0.2.0.0
  - rocksdb-haskell-1.0.1
  - strict-tuple-0.1.2
  - wai-middleware-throttle-0.3.0.0
  - yet-another-logger-0.3.1

  # --- Transitive Pact Dependencies --- #
  - ed25519-donna-0.1.1
  - sbv-8.2
  - swagger2-2.3.1.1

  # --- Other Transitive Dependencies --- #
  - base-compat-batteries-0.10.5 # Due to swagger2
  - contravariant-1.5.2  # Due to base-compat-batteries
  - libyaml-0.1.1.0      # Due to yaml
  - massiv-0.3.3.0       # Due to digraph
  - mwc-random-0.14.0.0  # Due to digraph
  - scheduler-1.3.0      # Due to massiv
  - token-bucket-0.1.0.1 # Due to wai-middleware-throttle

  # --- Forced Upgrades --- #
  - aeson-1.4.3.0
  - configuration-tools-0.4.1
  - generic-lens-1.1.0.0
  - nonempty-containers-0.2.0.0
  - tasty-1.2
  - tls-1.5.0
  - vector-algorithms-0.8.0.1
  - warp-tls-3.2.7  # To match `tls-1.5.0`
  - yaml-0.11.0.0

  # --- Custom Pins --- #
  - github: kadena-io/pact
    commit: d10173c574ae4dce1dae5a5dcbaf1ec4a9feb2c3
  - github: kadena-io/thyme
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
