#+TITLE: Mining for Chainweb
#+AUTHOR: Colin

* Table of Contents :TOC_4_gh:noexport:
- [[#what-is-mining][What is Mining?]]
- [[#chainweb-mining-via-official-kadena-software][Chainweb Mining via Official Kadena Software]]
  - [[#obtaining-a-key-pair][Obtaining a Key Pair]]
  - [[#mining-with-chainweb-node][Mining with chainweb-node]]
    - [[#basics][Basics]]
    - [[#disabling-the-in-process-miner][Disabling the In-Process Miner]]
    - [[#accepting-external-work-requests][Accepting External Work Requests]]
  - [[#mining-with-chainweb-miner][Mining with chainweb-miner]]
    - [[#basics-1][Basics]]
    - [[#chain-focusing][Chain Focusing]]
    - [[#log-suppression][Log Suppression]]
  - [[#troubleshooting][Troubleshooting]]
    - [[#i-mined-using-the-wrong-account-name][I mined using the wrong account name!]]
    - [[#i-mined-using-the-wrong-public-key][I mined using the wrong public key!]]
    - [[#chainweb-miner-says-that-i-mined-but-i-didnt-receive-the-reward][chainweb-miner says that I mined, but I didn't receive the reward.]]
    - [[#i-specify---chain-but-am-getting-work-for-other-chains-why][I specify ~--chain=...~ but am getting work for other chains. Why?]]
    - [[#why-am-i-being-preempted-so-much][Why am I being "preempted" so much?]]
- [[#remote-api-details][Remote API Details]]
  - [[#work-requests][Work Requests]]
  - [[#solution-submission][Solution Submission]]
  - [[#update-subscription][Update Subscription]]
  - [[#binary-formats][Binary Formats]]

* What is Mining?

A blockchain is a series of /blocks/. Blocks contain /transactions/ which
represent coin transfers or other Smart Contract interactions. Mining is the
process of mathematically "solving" a block. Unless solved, a block cannot be
included in the chain. Without mining, a blockchain cannot progress and
transactions will never finalize.

Economically, mining is the principle way to obtain currency on a Chainweb
network. Since Chainweb uses Proof-of-Work, computational effort is rewarded
with coins associated with each block you solve. The more computational power
you have, the more likely you are to be successful at mining.

Unlike blockchains that have a single chain, Chainweb has many. Everyone who
choses to mine can spread their effort across multiple chains, advancing each
chain equally, thereby reducing competition and wasted effort.

* Chainweb Mining via Official Kadena Software

There are two official ways to mine for a Chainweb network. The first is to use
~chainweb-node~ (a "full" Node) and perform in-process CPU mining alongside
other Node components. *This has the advantage of low-latency for getting new
work* since all databases are available on the same machine.

The second way is to use ~chainweb-miner~, our dedicated Mining Client. Work
requests are sent to known Nodes, who construct blocks for the client. Once
solved, the client returns the block to the Node for submission to the wider
network. This client boasts *much higher mining performance* and a *much simpler
setup*, since a ~chainweb-miner~ has no database connections and thus no storage
footprint.

For beginners, we recommend ~chainweb-miner~. Either way, you will need a Key
Pair before beginning.

** Obtaining a Key Pair

The easiest way to obtain a Key Pair is via the [[https://pact.kadena.io/][Pact Web]] application. Keys can
be generated by the /Wallet/ widget in the bottom-right. Once generated, take
note of the /Public Key/.

** Mining with chainweb-node

This assumes you have obtained a ~chainweb-node~ binary, the full setup
instructions forwhich will not be repeated here.

*** Basics

~chainweb-node~ has many configuration options. The following displays them all:

#+begin_src bash
  chainweb-node --print-config
#+end_src

In fact, a common pattern is to pipe this output to a file, and then immediately
reuse it:

#+begin_src bash
  chainweb-node --print-config > config.yaml
#+end_src

Doing so, we'll see the following configuration of your "mining identity":

#+begin_src yaml
  minerInfo:
    account: <your-account-name-here>  # This must be unowned, or already claimed by you!
    public-keys: [<your-public-key-here>]
    predicate: keys-all
#+end_src

With values specific to you replaced above (and the rest of Chainweb configured
correctly!) we're ready to mine:

#+begin_src bash
chainweb-node --config-file=config.yaml
#+end_src

By default, in-process mining is turned on. This means that while your Node is
servicing the overall network with Transaction, Peer, and Cut data, it will also
be passively mining.

*Note:* If your designated account did not previously exist, it will be created
the first time you successfully mine. If you specify an account name that you do
not own, you are *mining on that person's behalf*.

*** Disabling the In-Process Miner

If you want to run a Node without in-process mining:

#+begin_src bash
  chainweb-node --disable-mining ...  # other flags
#+end_src

*** Accepting External Work Requests

By default, a Node does *not* service external requests for new mining work, say
from a ~chainweb-miner~ or other third-party client. To turn this on:

#+begin_src bash
  chainweb-node --mining-coordination ... # other flags
#+end_src

This will open several endpoints that clients can call, which are described in
detail below. *Note:* Keep this option off if you aren't willing to have
anonymous clients connect to you for work generation calls. You won't be
rewarded for assembling blocks for them!

** Mining with chainweb-miner

Mining via ~chainweb-miner~ is much simpler, and generally promises better
results.

*** Basics

#+begin_src bash
  chainweb-miner cpu --cores=4 --node=<truted-node>:443 --miner-account=<you> --miner-key=<your-public-key>
#+end_src

Things to note:

- You can dedicate as many cores to parallel mining as you want with ~--cores~.
- You can only communicate with one Node at a time.
- As stated above, your declared account must be owned by you, or your rewards
  will go to someone else.

As mining progresses, you will see the following:

#+begin_example
  2019-09-16 16:57:22.311371: [info] Starting Miner.
  2019-09-16 16:57:58.349747: [info] 8: Current work was preempted.
  2019-09-16 16:58:25.702572: [info] 9: Current work was preempted.
  2019-09-16 16:58:37.289252: [info] 6: Mining Success!
  2019-09-16 16:58:48.749402: [info] 4: Current work was preempted.
#+end_example

The number next to the message represents the chain you were working on at that
time.

*** Chain Focusing

You might have a reason to prioritize one chain over the rest. To request that
the Node attempt to give you work for a specific chain first, pass ~--chain~:

#+begin_src bash
  chainweb-miner cpu --chain=9 ... # other flags
#+end_src

*** Log Suppression

You may only be interested in warning or error messages. If so, use the
~--log-level~ flag:

#+begin_src bash
  chainweb-miner cpu --log-level=warn ... # other flags
#+end_src

#+begin_example
  2019-09-16 16:57:56.755636: [warn] Couldn't connect to update stream. Trying again...
  2019-09-16 16:58:23.646547: [error] Failed to fetch work! Is the Node down?
#+end_example

** Troubleshooting

*** I mined using the wrong account name!

If the incorrect account was previously unclaimed, then you now own that one
too. Otherwise, you've just mined on someone else's behalf, and have lost your
coins.

*** I mined using the wrong public key!

If you already owed the account, you will still be rewarded. Otherwise, you have
locked your coins into a new account that nobody can access.

*** chainweb-miner says that I mined, but I didn't receive the reward.

This?

#+begin_example
  2019-09-16 16:58:37.289252: [info] 6: Mining Success!
#+end_example

And yet your balance on Chain 6 remains unchanged?

Mining is a big race. Even if you succeeded on Chain 6, by the time your block
returned to the Node, the Node may have already registed a faster block.

#+begin_quote
But if it knew about a better block on my chain, why didn't it preempt me?
#+end_quote

Race conditions. There's a small time window between the Node processing the
faster block, telling you about it, and you submitting your own block. Consider
it bad luck.

*** I specify ~--chain=...~ but am getting work for other chains. Why?

It is fundamental to the design of Chainweb that chains cannot progress much
further than their neighbour chains. It may be that by asking for ~--chain=9~,
the Node couldn't find work to do! In this case, it falls back to picking a
random chain. This balances the needs of the Miner, who may want a specific
Chain to progress efficiently, with the needs of the network, who requires all
chains to grow evenly.

*** Why am I being "preempted" so much?

This?

#+begin_example
  2019-09-16 17:30:11.791641: [info] 7: Current work was preempted.
  2019-09-16 17:30:15.759249: [info] 8: Current work was preempted.
  2019-09-16 17:30:27.340109: [info] 9: Current work was preempted.
  2019-09-16 17:30:57.343577: [info] 6: Current work was preempted.
  2019-09-16 17:31:04.998382: [info] 9: Current work was preempted.
  2019-09-16 17:31:14.649440: [info] 1: Current work was preempted.
  2019-09-16 17:31:25.503355: [info] 4: Current work was preempted.
  2019-09-16 17:31:45.471371: [info] 9: Current work was preempted.
  2019-09-16 17:31:56.940698: [info] 2: Current work was preempted.
  2019-09-16 17:32:16.807348: [info] 9: Current work was preempted.
  2019-09-16 17:32:21.721842: [info] 8: Current work was preempted.
#+end_example

This is normal. This means that other miners are beating you, and that you
probably don't hold much of the overall network hash power.

* Remote API Details

** Work Requests

** Solution Submission

** Update Subscription

** Binary Formats
