#+TITLE: Mining with Chainweb
#+AUTHOR: Colin

* Table of Contents :TOC_4_gh:noexport:
- [[#what-is-mining][What is Mining?]]
- [[#usage][Usage]]
  - [[#obtaining-a-key-pair][Obtaining a Key Pair]]
  - [[#mining-with-chainweb-node][Mining with ~chainweb-node~]]
    - [[#basics][Basics]]
    - [[#disabling-the-in-process-miner][Disabling the In-Process Miner]]
    - [[#accepting-external-work-requests][Accepting External Work Requests]]
  - [[#mining-with-chainweb-miner][Mining with ~chainweb-miner~]]
    - [[#basics-1][Basics]]
    - [[#chain-focusing][Chain Focusing]]
  - [[#troubleshooting][Troubleshooting]]
    - [[#i-mined-using-the-wrong-account-name][I mined using the wrong account name!]]
    - [[#i-mined-using-the-wrong-public-key][I mined using the wrong public key!]]
    - [[#chainweb-miner-says-that-i-mined-but-i-never-received-the-reward][~chainweb-miner~ says that I mined, but I never received the reward.]]
    - [[#i-specify---chain-but-am-getting-work-for-other-chains-why][I specify ~--chain=...~ but am getting work for other chains. Why?]]
    - [[#why-am-i-being-preempted-so-much][Why am I being "preempted" so much?]]
- [[#remote-api-details][Remote API Details]]
  - [[#work-requests][Work Requests]]
  - [[#solution-submission][Solution Submission]]
  - [[#update-subscription][Update Subscription]]
  - [[#binary-formats][Binary Formats]]

* What is Mining?

A blockchain is a series of /blocks/. Blocks contain /transactions/ which
represent coin transfers or other Smart Contract interactions. Mining is the
process of mathematically "solving" a block. Unless solved, a block cannot be
included in the chain. Without mining, a blockchain cannot progress and
transactions will never finalize.

Economically, mining is the principle way to obtain currency on a Chainweb
network. Since Chainweb uses Proof-of-Work, computational effort is rewarded
with coins associated with each block you solve. The more computational power
you have, the more likely you are to be successful at mining.

Unlike blockchains that have a single chain, Chainweb has many. Everyone who
choses to mine can spread their effort across multiple chains, advancing each
chain equally, thereby reducing competition and wasted effort.

* Usage

There are two ways to mine for a Chainweb network. The first is to use
~chainweb-node~ (a "full" Node) and perform in-process CPU mining alongside
other Node components. *This has the advantage of low-latency for getting new
work* since all databases are available on the same machine.

The second way is to use ~chainweb-miner~, our dedicated Mining Client. Work
requests and sent to known Nodes, who contruct blocks for the client. Once
solved, the client returns the block to the Node for submission to the wider
network. This client boasts *much higher mining performance* and a *much simpler
setup*, since a ~chainweb-miner~ has no database connections and thus no storage
footprint.

Either way, you will need a Key Pair before beginning.

** Obtaining a Key Pair

The easiest way to obtain a Key Pair is via the [[https://pact.kadena.io/][Pact Web]] application. Keys can
be generated by the /Wallet/ widget in the bottom-right. Once generated, take
note of the /Public Key/.

** Mining with ~chainweb-node~

*** Basics
*** Disabling the In-Process Miner
*** Accepting External Work Requests

** Mining with ~chainweb-miner~

*** Basics

*** Chain Focusing

** Troubleshooting

*** I mined using the wrong account name!

*** I mined using the wrong public key!

*** ~chainweb-miner~ says that I mined, but I never received the reward.

*** I specify ~--chain=...~ but am getting work for other chains. Why?

*** Why am I being "preempted" so much?

* Remote API Details

** Work Requests

** Solution Submission

** Update Subscription

** Binary Formats
